spring:
  application:
    name: 'api-gateway'
  output:
    ansi:
      enabled: ALWAYS
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://service-discovery:8761/eureka}
server:
  port: ${SERVER_PORT:8765}