spring:
  application:
    name: email-service
  cloud:
    config:
      name: email-service
      uri: ${CONFIG_SERVER_URI:http://config-server:8888}
      fail-fast: true
  output:
    ansi:
      enabled: Always
  profiles:
    active: ${PROFILE_ACTIVE:dev}
  rabbitmq:
    addresses: rabbitmq:5672
    host: rabbitmq
    port: 5672
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
mail:
  host: ${MAIL_HOST:smtp.gmail.com}
  port: ${MAIL_PORT:587}
  username: ${MAIL_USERNAME}
  password: ${MAIL_PASSWORD}
  protocol: ${MAIL_PROTOCOL:smtp}
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI}

server:
  port: ${PORT:9090}